name: Bug Report 🐞
description: Report a malfunction of the plugin
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting the bug! Please help us understand what is going wrong.
  
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: Describe what is happening.
      placeholder: E.g., The fader does not return to zero when I change pages...
    validations:
      required: true

  - type: dropdown
    id: ma3-version
    attributes:
      label: grandMA3 Version
      options:
        - 2.4.2
        - 2.3.x
        - Other
    validations:
      required: true

  - type: input
    id: chataigne-version
    attributes:
      label: Chataigne Version
      placeholder: 1.10.3
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: System Logs
      description: Paste any errors seen in the MA3 System Monitor or Chataigne Logger here.
      render: text
